name: memes
services:
  # postgres:
  #   image: postgres:16
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"      
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - memes-networks
  

  private_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:  bash -c 'uvicorn private_api.main:app --reload --port 8001'
    ports:
      - "8001:8001"
    volumes:
      - ./private_api:/mad_test/private_api
    environment:
      - MINIO_URL=http://minio:9000
    depends_on:
      - "minio"
    networks:
      - memes-networks

  # public_api:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   command:  bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done;
  #     alembic -c alembic.ini upgrade head;
  #     uvicorn public_api.main:app --reload --port 8000'
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./public_api:/mad_test/public_api
  #   environment:
  #     - POSTGRES_HOST=postgres
  #   depends_on:
  #     - "postgres"
  #     - "private_api"
  #   networks:
  #     - memes-networks
  
  minio:
    image: minio/minio
    command: server /data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
    networks:
      - memes-networks

networks:
  memes-networks:
    driver: bridge

volumes:
  postgres-data:
  minio-data: