"""Create user table

Revision ID: 472f5accbc6b
Revises: 
Create Date: 2024-06-18 12:53:43.531660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472f5accbc6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memes_id', table_name='memes')
    op.drop_index('ix_memes_image_url', table_name='memes')
    op.drop_index('ix_memes_text', table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='memes_pkey')
    )
    op.create_index('ix_memes_text', 'memes', ['text'], unique=False)
    op.create_index('ix_memes_image_url', 'memes', ['image_url'], unique=True)
    op.create_index('ix_memes_id', 'memes', ['id'], unique=False)
    # ### end Alembic commands ###
